<?php

namespace ClienteBundle\Repository;

/**
 * ClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClienteRepository extends \Doctrine\ORM\EntityRepository
{
    public function listarClientes()
    {
        $qb = $this->createQueryBuilder('c')
                ->innerJoin('c.grupo', 'g');
        
	    return $qb->getQuery();
    }

    public function buscarClientes($search)
    {
        $qb = $this->createQueryBuilder('c');
        $qb ->innerJoin('c.grupo', 'g')
            ->where($qb->expr()
                ->like('c.nombre', $qb->expr()
                    ->literal('%'.$search.'%')))
            ->orWhere($qb->expr()
                ->like('c.apellido', $qb->expr()
                    ->literal('%'.$search.'%')));
        
	    return $qb->getQuery()->getResult();
    }
}